INSERT INTO customers(id, name, billingAddress, customerBalance, customerActivated)
VALUES (1, 'C. U. Stomer', 'Address 1', 100.24, CURRENT_TIMESTAMP());
INSERT INTO customers(id, name, billingAddress, customerBalance, customerActivated)
VALUES (2, 'Cus Tomer', 'Address 3', 10.78, CURRENT_TIMESTAMP());
INSERT INTO customers(id, name, billingAddress, customerBalance, customerActivated)
VALUES (3, 'Cu Sto Mer', 'Address 45', 300.22, CURRENT_TIMESTAMP());


INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 12.34, 'Channel #123', 1);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 25.55, 'Channel #40', 3);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 1.74, 'Channel #35', 2);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 1.15, 'Channel #17', 2);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 45.69, 'Channel #29', 1);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 7.59, 'Channel #39', 3);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 3.50, 'Channel #16', 3);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 14.79, 'Channel #39', 2);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 15.27, 'Channel #40', 2);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 4.38, 'Channel #37', 2);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 2.78, 'Channel #16', 1);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 10.68, 'Channel #26', 3);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 6.00, 'Channel #14', 2);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 6.78, 'Channel #22', 3);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 10.29, 'Channel #36', 1);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 13.20, 'Channel #11', 2);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 11.20, 'Channel #33', 1);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 37.13, 'Channel #29', 2);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 32.86, 'Channel #33', 1);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 23.31, 'Channel #34', 1);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 0.92, 'Channel #29', 3);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 22.91, 'Channel #27', 2);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 14.93, 'Channel #35', 2);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 5.17, 'Channel #20', 3);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 14.22, 'Channel #30', 3);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 2.94, 'Channel #10', 1);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 7.66, 'Channel #13', 3);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 7.47, 'Channel #29', 3);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 26.88, 'Channel #22', 3);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 0.94, 'Channel #27', 1);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 4.77, 'Channel #38', 1);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 13.25, 'Channel #39', 1);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 6.06, 'Channel #32', 1);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 1.21, 'Channel #15', 3);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 4.11, 'Channel #30', 2);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 0.12, 'Channel #30', 1);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 0.99, 'Channel #17', 2);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 40.10, 'Channel #11', 1);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 15.35, 'Channel #15', 1);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 2.04, 'Channel #34', 1);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 6.51, 'Channel #34', 2);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 1.96, 'Channel #10', 2);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 0.03, 'Channel #35', 2);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 11.77, 'Channel #30', 1);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 7.78, 'Channel #22', 2);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 9.19, 'Channel #14', 3);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 6.51, 'Channel #28', 3);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 0.88, 'Channel #26', 3);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 21.98, 'Channel #37', 2);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 14.32, 'Channel #11', 1);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 24.51, 'Channel #22', 3);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 0.28, 'Channel #37', 1);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 2.68, 'Channel #29', 2);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 2.29, 'Channel #14', 2);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 23.20, 'Channel #27', 3);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 3.98, 'Channel #22', 2);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 2.72, 'Channel #39', 1);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 21.99, 'Channel #12', 3);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 11.10, 'Channel #39', 1);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 15.57, 'Channel #17', 2);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 8.32, 'Channel #15', 1);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 11.71, 'Channel #38', 3);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 5.11, 'Channel #17', 2);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 8.04, 'Channel #30', 3);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 7.47, 'Channel #37', 1);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 14.35, 'Channel #31', 3);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 21.44, 'Channel #35', 2);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 1.11, 'Channel #16', 3);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 25.82, 'Channel #15', 2);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 2.77, 'Channel #30', 3);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 2.65, 'Channel #34', 2);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 14.07, 'Channel #33', 3);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 3.63, 'Channel #25', 1);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 11.72, 'Channel #39', 2);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 10.61, 'Channel #14', 1);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 3.45, 'Channel #22', 1);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 4.70, 'Channel #19', 1);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 15.47, 'Channel #29', 2);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 1.96, 'Channel #33', 1);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 25.50, 'Channel #14', 1);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 2.28, 'Channel #24', 3);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 8.78, 'Channel #40', 2);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 10.39, 'Channel #23', 2);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 2.44, 'Channel #27', 1);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 0.77, 'Channel #23', 3);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 3.39, 'Channel #15', 3);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 2.14, 'Channel #39', 3);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 17.01, 'Channel #31', 3);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 1.92, 'Channel #23', 1);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 2.94, 'Channel #16', 3);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 29.05, 'Channel #40', 3);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 15.19, 'Channel #30', 1);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 30.98, 'Channel #16', 2);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 6.01, 'Channel #23', 3);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 35.81, 'Channel #19', 2);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 3.16, 'Channel #32', 3);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 1.26, 'Channel #14', 1);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 28.96, 'Channel #36', 1);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 30.18, 'Channel #20', 3);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 6.40, 'Channel #38', 3);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 11.21, 'Channel #13', 2);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 11.20, 'Channel #14', 1);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 8.40, 'Channel #35', 2);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 4.58, 'Channel #33', 2);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 33.36, 'Channel #12', 1);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 7.42, 'Channel #30', 1);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 3.46, 'Channel #15', 3);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 15.92, 'Channel #31', 3);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 36.23, 'Channel #36', 1);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 16.43, 'Channel #36', 2);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 1.44, 'Channel #28', 1);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 30.58, 'Channel #38', 1);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 14.54, 'Channel #35', 3);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 40.00, 'Channel #14', 3);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 7.78, 'Channel #34', 2);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 9.36, 'Channel #17', 2);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 15.37, 'Channel #16', 2);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 0.75, 'Channel #39', 3);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 24.42, 'Channel #12', 2);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 6.52, 'Channel #39', 2);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 7.31, 'Channel #15', 3);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 25.85, 'Channel #13', 1);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 15.23, 'Channel #29', 3);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 27.27, 'Channel #27', 1);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 16.30, 'Channel #26', 2);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 0.36, 'Channel #19', 2);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 14.70, 'Channel #25', 2);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 9.98, 'Channel #16', 1);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 10.75, 'Channel #20', 1);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 20.03, 'Channel #35', 3);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 49.71, 'Channel #26', 1);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 40.03, 'Channel #14', 3);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 0.54, 'Channel #40', 3);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 14.80, 'Channel #29', 3);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 0.38, 'Channel #34', 1);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 11.92, 'Channel #32', 1);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 3.10, 'Channel #27', 2);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 10.49, 'Channel #25', 2);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 6.43, 'Channel #13', 3);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 38.20, 'Channel #16', 2);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 7.47, 'Channel #20', 2);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 2.54, 'Channel #29', 3);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 7.30, 'Channel #24', 1);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 4.88, 'Channel #22', 3);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 13.69, 'Channel #34', 3);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 19.29, 'Channel #33', 2);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 24.84, 'Channel #24', 1);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 6.32, 'Channel #30', 2);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 26.28, 'Channel #20', 1);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 39.16, 'Channel #36', 3);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 1.46, 'Channel #37', 3);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 4.12, 'Channel #17', 1);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 0.83, 'Channel #22', 1);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 12.25, 'Channel #29', 2);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 37.46, 'Channel #23', 3);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 24.10, 'Channel #20', 1);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 2.36, 'Channel #40', 3);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 8.42, 'Channel #23', 3);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 0.76, 'Channel #20', 3);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 5.56, 'Channel #29', 1);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 1.45, 'Channel #19', 1);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 1.26, 'Channel #28', 2);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 0.41, 'Channel #11', 3);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 0.69, 'Channel #34', 1);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 12.56, 'Channel #31', 2);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 0.59, 'Channel #25', 2);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 32.39, 'Channel #22', 1);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 9.48, 'Channel #40', 1);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 15.80, 'Channel #38', 1);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 37.19, 'Channel #28', 2);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 33.96, 'Channel #24', 3);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 13.09, 'Channel #36', 2);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 8.09, 'Channel #19', 1);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 32.45, 'Channel #12', 1);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 33.58, 'Channel #32', 3);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 17.76, 'Channel #24', 3);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 3.99, 'Channel #12', 3);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 2.43, 'Channel #21', 3);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 0.28, 'Channel #27', 2);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 0.37, 'Channel #40', 3);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 1.14, 'Channel #40', 1);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 4.48, 'Channel #33', 2);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 27.20, 'Channel #33', 2);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 33.28, 'Channel #33', 1);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 0.99, 'Channel #37', 3);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 13.99, 'Channel #26', 2);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 13.10, 'Channel #13', 2);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 5.31, 'Channel #16', 2);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 16.50, 'Channel #13', 2);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 17.60, 'Channel #40', 1);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 0.37, 'Channel #22', 1);
INSERT INTO payments(paymentDate, paymentAmount, channel, customerID)
VALUES (CURRENT_TIMESTAMP(), 0.11, 'Channel #35', 2);
